[dependencies]
# Backend
actix-web = "4.0"
surrealdb = { version = "1.0.0-beta.8", features = ["ws"] }
tokio = { version = "1", features = ["full"] }

# Frontend (Leptos)
leptos = "0.4"
leptos-actix = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"